### ISSUE TITLE
Support PHP

### ISSUE THREAD

**Issue by e3rd** [markiewb/nb-copy-fqn#11]
Hello, would it be easy to make this plugin support PHP as well, or it would need completely different approach?

**Comment by markiewb** [comment]
Hej @e3rd, I am sorry to tell that I won't support PHP within this plugin. There is no common API for that. The plugin uses NetBeans APIs to get the FQN from Java Sources only. The PHP API for that is quite different. I have no time to support this too.

**Comment by markiewb** [comment]
I also don't use PHP, so I would not even use it in my daily work nor find bugs in it...

**Comment by e3rd** [comment]
Just asking, thank for your reply ;)
